# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f695673b62fb75839b7d9e750644e321cd8718db936ef2110bf332be8444fe2610c0151ba92cf1c98cb893296f90ba6ceba467718d9ca3e16c05f558cfcdd27

test:
  secret_key_base: 11119b368cb80eace72aafa98e54f6d138bfa805d4deb1d455a2c482eebaf3347daf51539f646bd206433ef2eaf89a8ecea638da906ae5181bbfb7805dcc7042

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
